[features]
seeds = false
skip-lint = false
[programs.localnet]
carbon_bazaar = "CLZYui5NQzCFABeiVHujBKzDpYYwb5wmBeGeNdSkkpjc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
